import { ProviderTanstack, ProviderAuth } from '@providers';

import '../../public/global.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <ProviderTanstack>
          <ProviderAuth>{children}</ProviderAuth>
        </ProviderTanstack>
      </body>
    </html>
  );
}
