import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import Header from 'components/Header';
import Nav from 'components/common/Nav';

import { ProviderAuth } from 'hooks/useAuth';
import '../styles/global.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IProps) {
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <ProviderAuth>
            <div className="min-h-full">
              <Header />
              <Nav />
              <main className="max-w-7xl mx-auto py-6 sm:px-6 xl:px-8">{children}</main>
            </div>
          </ProviderAuth>
        </QueryClientProvider>
      </body>
    </html>
  );
}
